title: Your Title
email: your-email@example.com
description: >-
  My personal Jekyll site.

# Essential for GitHub Pages
url: "https://jmathiesonwork311-pixel.github.io"
baseurl: ""

# Theme Settings
remote_theme: "nrandecker/particle"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-remote-theme